services:
  - type: web
    name: coach-mohamed-ali
    runtime: static
    buildCommand: ""
    staticPublishPath: .
    headers:
      - path: /*
        name: Cache-Control
        value: public, max-age=0, must-revalidate
      - path: /icons/*
        name: Cache-Control
        value: public, max-age=31536000, immutable
      - path: /css/*
        name: Cache-Control
        value: public, max-age=31536000, immutable
    routes:
      - type: rewrite
        source: /*
        destination: /index.html
